name: Push to wordstat-rs repository
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build library
      run: cargo build --release

  tests:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build tests
      run: cargo build --tests
    - name: Run tests
      run: cargo test

  docs:
    needs: [build, tests]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - name: Setup rust
      uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build docs
      run: cargo doc

